; PIOarduino Project Configuration File
; FilamentSense: ESP32 + Arduino framework

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino

; upload_port = /dev/ttyACM0
; monitor_port = /dev/ttyACM0
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -D CORE_DEBUG_LEVEL=0

lib_deps =
    bogde/HX711 @ ^0.7.5