; PlatformIO Project Configuration File
; FilamentSense: ESP32 + Arduino framework

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bogde/HX711 @ ^0.7.5
build_flags =
  -D CORE_DEBUG_LEVEL=0
