[wokwi]
version = 1
firmware = ".pio/build/esp32c6/firmware.bin"
elf = ".pio/build/esp32c6/firmware.elf"
gdbServerPort = 3333

# Create diagram.json in the project root to describe ESP32, HX711, and buttons wiring.
diagram = "diagram.json"
